### ISSUE TITLE
Remove entities

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#10]
Currently there is no way to delete an entity.

**Comment by ymajoros** [comment]
Most cannot be deleted, but should have an 'active' flag and/or 0 stock for
items.

**Comment by cghislai** [comment]
That should probably be ready for beta, at least for Sale / SaleItem / SaleAccountingEntry

**Comment by cghislai** [comment]
See pull request #26

**Comment by ymajoros** [comment]
To delete a sale, just DELETE /sale/{id}. I deprecated DELETE /sale/{id}/state/open.

The backend should check the state and throw a bad request if you can't delete it.

The frontend should know it anyway and only allow deleting open sales.

Validation can later be down with pure Bean Validation, with a 'delete' validation groups that doesn't allow it to be open. That's for later.

**Comment by ymajoros** [comment]
Closing to keep things simple. Please open a new issue for things you want to be able to delete / inactivate. Just do it when needed, not too much in advance for every possible entity.
