### ISSUE TITLE
Frontend: sale history doesn't work

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#101]
For most sales, I don't get any item in the list.

For some other, same + ajax icon animation stays.

There are some errors in console. I'll attach the logs.

**Comment by ymajoros** [comment]
[localhost-1446791391709.log.txt](https://github.com/Valuya/comptoir/files/28659/localhost-1446791391709.log.txt)

**Comment by cghislai** [comment]
It works just fine here. No error in the requests?
I will check Lifecycle.tick errors (should not prevent showing the table though).

**Comment by cghislai** [comment]
works correctly in branch angular2-beta0
