### ISSUE TITLE
Frontend: blank screen after some inactivity

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#102]
I somehow got in a situation were nothing worked (blank screen). Nothing in console.

The only thing that got me out was clearing "local storage" in Chrome.

This is a show-stopper, I don't expect users to do that. 

Redirect to login screen if necessary, but never display a blank page.

**Comment by cghislai** [comment]
I have commit a fix in master.
The issues is probably coming from the angular2 router, which does not handle correctly (yet) default redirects (path: '/', redirectTo:'/Sales/Actives').
To prevent the issue
- When navigating to an empty path, a manual redirect to active sales is performed
- A timeout to refresh the token in case of inactivity is set up
- The token is still checked and refreshed (if required) on each navigation
