### ISSUE TITLE
cannot enter 2 new products in sale

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#109]
If we sell 2 different products that are not in catalog, there is no way to have 2 lines in ticket to enter 2 different comments, with each its own price etc.

**Comment by cghislai** [comment]
Fixed in https://github.com/Valuya/comptoir-front/commit/130c053a2c35f1f700ccbc2d0203d23ebb6e24ef

**Comment by ymajoros** [comment]
Still not working: bad request on save.

**Comment by ymajoros** [comment]
Ok, I got a bad request only when not entering a vat value. 

Even when doing so, it seems that the item is not found afterwards:
- entering an item with ref xxxx
- saving
- searching for xxxx

--> doesn't succeed; backend problem, I guess.

**Comment by ymajoros** [comment]
Besides that, I can't add a newly created product to a sale: I get an empty variant selection screen.

**Comment by ymajoros** [comment]
Someone else is interested in this and asked for a demo, so this could be urgent :-/

**Comment by cghislai** [comment]
Let's split these issues:
- Item search sometimes fails
- Item without variant are allowed

I cannot find any issue with multiple_sale items, so I close this one
