### ISSUE TITLE
Entering payment should work with a button too. 

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#110]
We now have to press ENTER, but a green button would be nice too.

**Comment by ymajoros** [comment]
10 € gives 9.99. Sometimes 10.00.

**Comment by cghislai** [comment]
I cannot reproduce on https://github.com/Valuya/comptoir-front/commit/ea611ff258e5d730d415fa136e303e93984c2907

**Comment by cghislai** [comment]
Oh and the buttons were added :)

**Comment by ymajoros** [comment]
Nice, I'll try the latest version :-)

Le ven. 29 janv. 2016 à 15:37, cghislai <notifications@github.com> a écrit :

> Oh and the buttons were added :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/110#issuecomment-176785554>.
>
-- 
Yannick Majoros
Valuya sprl
