### ISSUE TITLE
Front-end(?): rounding problems

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#111]
Entering 41 € as prices gives 40.99 €. 41.01 gives 41.01. Not sure, but I think it's a front-end problem.

**Comment by ymajoros** [comment]
FYI, I'm on commit 92a33f3.

**Comment by cghislai** [comment]
Ok,
Just for information, when we edit a price, we edit the vat-included amount. Prices are stored in db as vat_exclusive amount (2 decimals) and vat_rate (2 decimals).
I think it is not always possible to find a vat_exclusive amount that would give the entered price once vat rate is applied and the result rounded to 2 decimals.
Any thought on this?

**Comment by cghislai** [comment]
Simple example with 0.21 vat rate : When entering 41, the frontend computes 41/1.21=33.8843=33.88.
The itemVariantSale is updated and sent to backend.
It is then re-fetched for totals and the front-end recomputes the vat_inclusive amount: 33.88 * 1.21 = 40.9948 = 40.99

**Comment by ymajoros** [comment]
Seems reasonable. I'll need to talk with the customer and/or the accountant.

An easy fix, if possible, is just to allow more decimals, and just round
the total. I'll check what the law says about it.

Le ven. 29 janv. 2016 à 15:47, cghislai <notifications@github.com> a écrit :

> Simple example with 0.21 vat rate : When entering 41, the frontend
> computes 41/1.21=33.8843=33.88.
> The itemVariantSale is updated and sent to backend.
> It is then re-fetched for totals and the front-end recomputes the
> vat_inclusive amount: 33.88 * 1.21 = 40.9948 = 40.99
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/111#issuecomment-176790877>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
I just pushed changes in the frontend : we keep up to 5 decimals when sending an item price.
The unit price is retrived as it, thus it can be rounded correctly.
However, the total (vat exclusive) price, as computed by the backend, is rounded to 2 decimals.
I prefer to wait for your accountant feedback before touching the AccountingUtils calculations.
I can however compute the total in the frontend to get it working more quickly.

**Comment by ymajoros** [comment]
Let's fix the backend and stick to 4 decimals everywhere.

Le dim. 31 janv. 2016 à 17:23, cghislai <notifications@github.com> a écrit :

> I just pushed changes in the frontend : we keep up to 5 decimals when
> sending an item price.
> The unit price is retrived as it, thus it can be rounded correctly.
> However, the total (vat exclusive) price, as computed by the backend, is
> rounded to 2 decimals.
> I prefer to wait for your accountant feedback before touching the
> AccountingUtils calculations.
> I can however compute the total in the frontend to get it working more
> quickly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/111#issuecomment-177541506>.
>
-- 
Yannick Majoros
Valuya sprl
