### ISSUE TITLE
Frontend: allow reopening sale.

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#114]
We must somehow be able to reopen a past sale. I'll handle the backend. This needs some book keeping / stock handling (later) to be correct: cancelling the sale, payments, ...

On the front side, create a button to reopen a sale that will call the service in backend.

For now, just allow editing past sales just after clicking on the reopen button (that still doesn't do any backend call).

**Comment by cghislai** [comment]
I've pushed the UI changes in the frontend. I let you check the backend then.

**Comment by cghislai** [comment]
On hold until backend resource is available
