### ISSUE TITLE
What should we merge?

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#116]
I'm lost between the 4 different repos (yours, mine, front/back), branches, ...

**Comment by cghislai** [comment]
Lets use valuya/comptoir and valuya/comptoir-front as the base repositories

**Comment by ymajoros** [comment]
Do you think we should merge them to have 1 repository for the whole
application?

Le ven. 29 janv. 2016 à 15:31, cghislai <notifications@github.com> a écrit :

> Lets use valuya/comptoir and valuya/comptoir-front as the base repositories
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/116#issuecomment-176782292>.
>
-- 
Yannick Majoros
Valuya sprl
