### ISSUE TITLE
Customer Loyalty

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#121]
Every time a customer buys something, 10% (configurable) of the amount of full-price articles goes on his loyalty account (= special customer account). This happens at sale close, and is somehow a link to sale ± custom adjustment (like, - 5 €). By link, I mean we should always able to recalculate everything, should a sale be cancelled at a later time or whatever.

A customer can pay with his loyalty account.

**Comment by cghislai** [comment]
Just to be sure:
- Customer
-- loyaltyRate
- CustomerLoyaltyAccountEntry
-- customerRef
-- saleRef
-- dateTime
-- customAmount
-- payment: boolean

Then, on sale close, the amount is set

**Comment by ymajoros** [comment]
Loyalty rate is normally general. There can be a specific one by customer, but that won't happen too much.

What's "customAmount"?

Everything should be mostly automatic, but you can always exclude some articles (e.g. on sale articles should be excluded, you could choose others manually).

**Comment by cghislai** [comment]
"What's "customAmount"?":
When you were saying 'custom adjustment', I thought the user should be able to add a custom loyalty amount when closing a sale

"you can always exclude some articles (e.g. on sale articles should be excluded, you could choose others manually).":
I'm not sure I understand correctly.
Articles should be marked as accounted for loyalty accounts and the user should be able to overwrite this for a given sale, right?

**Comment by ymajoros** [comment]
I meant, you can always uncheck some item from customer loyalty. Or check
one that wasn't taken by default (e.g. items with rebates).

Le jeu. 24 mars 2016 à 08:45, cghislai <notifications@github.com> a écrit :

> "What's "customAmount"?":
> When you were saying 'custom adjustment', I thought the user should be
> able to add a custom loyalty amount when closing a sale
>
> "you can always exclude some articles (e.g. on sale articles should be
> excluded, you could choose others manually).":
> I'm not sure I understand correctly.
> Articles should be marked as accounted for loyalty accounts and the user
> should be able to overwrite this for a given sale, right?
>
> —
> You are receiving this because you were assigned.
>
>
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/121#issuecomment-200707349>
>
-- 
Yannick Majoros
Valuya sprl
