### ISSUE TITLE
Counting cash: allow custom amount

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#123]
Instead of telling how many of each 1/2/5 € I have, let's also have a free field to count money.

**Comment by cghislai** [comment]
You can do that by editing the total field directly.
Is any UI improvement welcome?

**Comment by ymajoros** [comment]
Didn't knew that, perfect :-)

Le ven. 29 janv. 2016 à 15:30, cghislai <notifications@github.com> a écrit :

> You can do that by editing the total field directly.
> Is any UI improvement welcome?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/123#issuecomment-176781766>.
>
-- 
Yannick Majoros
Valuya sprl
