### ISSUE TITLE
Improve dockerization

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#124]
- there is still no db backup, we really need one
- we need to be able to deploy from jenkins, let's expose GF's 4848 (I'll probably handle this one)
- logs should be backuped as well
- network instead of links
- have it restart at boot if it doesn't (could just be a flag at docker run time)
- maybe use docker-compose to start the whole thing
- prepare it to be easily movable to another server (prod.valuya.be)

**Comment by cghislai** [comment]
Reassigning you for review and to setup host crontab and logrotate.
- comptoirdev_* containers are set up and running on development server
- deployment is handled by jenkins container
- backup script is in my home: ~/docker-compose/run/comptoir/backup.sh (use 'dev' argument)
- backup files are located in /opt/docker/backup/comptoir-dev/[timestring]/

**Comment by ymajoros** [comment]
I'm thinking about starting backups from jenkins...

**Comment by cghislai** [comment]
Closing as it is not applicable anymore. There is a decent solution in the swarm branches of our private docker repos.
