### ISSUE TITLE
 Balance / MoneyPile

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#13]
To implement

**Comment by ymajoros** [comment]
Added balance resource.

Actually, we'll need to think about it: moneyPile should create balance by backend, so no need to create it from front.

--> Balance POST/(PUT?) shouldn't be needed right now, maybe later to integrate bank statements.

**Comment by ymajoros** [comment]
Opening a new issue for MoneyPile.

**Comment by ymajoros** [comment]
Forget about my POST comment: you should create a Balance from front (POST), then add MoneyPile entries.

Backend will adjust balance.

Still need some way to store what's counted vs what should be there.

**Comment by cghislai** [comment]
I implemented that in the frontend. Im puzzled how you will link the balance to a sale. For now the flow is as following:
- create a Sale
- as ItemSale, fetch back updated ItemSale and Sale
for the payment
- chose an account to pay from
- create a balance for that account
- create a money pile with some content for that balance, fetch back the updated balance 
- close the balance
- close the sale

**Comment by ymajoros** [comment]
Balance is what we do at the end of the day (=counting MoneyPiles). Payment should happen with AccountingEntry. I thought about a Payment resource, but it would have everything that AccountingEntry has.

**Comment by ymajoros** [comment]
See #13 -> Balance / MoneyPile are not intended for payment but to count
money at the end of the day.

**Comment by cghislai** [comment]
I reopen because the backend doesn't seem to update the balance yet once moneypiles are added.

**Comment by ymajoros** [comment]
No, it doesn't yet ;-) But your frontend is probably ok.
