### ISSUE TITLE
Backend: Stock entries for 'multipleSale' items

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#134]
We have items marked as 'multipleSale'  which are not grouped for sales and are currently used for unknown items.
Should they be handled in stocks as well?

If I understand correctly, we did not group them because they might actually be different objects. So they should not have stock entries, as they would then share the same stock.

Currently, if a 'multipleSale' item is added twice to a sale, two ItemStock entries are created simultaneously once the sale is closed.

**Comment by ymajoros** [comment]
I think they should be handled as multiple stock movements.

I guess unknown items will have 0 as initial stock. Let's be coherent and decrement the stock, so we'll probably get negative values.

Eventually, unknown item sales should be converted to normal item sales anyway. We will need some workflow. e.g.: if I sell something that's not in my inventory, I'll file this as unknown item sale, add a description, and later correct that by adding the item to the stock, reopening the sale, adjusting stocks somehow :-/

**Comment by cghislai** [comment]
So it works correctly in master, except for one thing : The stock entries are created simultaneously, so sorting the entries by date does not give the expected result.

I guess this should be fixed in backend, but I'm not sure how
- Ensuring two stock entries do not share the same startDateTime?
- Allowing to sort by logical order, i.e. through the previousStockItem references?
- Get the current entry in frontend and sort the list throught previousItem references? 
Any thought?

**Comment by ymajoros** [comment]
I can't follow: which stock entries are created simultaneously?

**Comment by cghislai** [comment]
Once a sale is closed, for multipleSale items, multiple stock entries are
created simultaneously. (One per ItemVariantSale)

**Comment by ymajoros** [comment]
Still, I don't see any problem here. I guess they are all created solely by the backend, and have the exact same date coming from the same date instance. Sorting them by date just doesn't make sense.

**Comment by cghislai** [comment]
The issue is for displaying the list of stock entries in the frontend. With such items, we get something like:

[date] [type] [amout]
12:01 Sale  5
12:01 Sale 4
12:01 Sale 3
11:02 Adjustement 6

While we expect:
[date] [type] [amout]
12:01 Sale  3
12:01 Sale 4
12:01 Sale 5
11:02 Adjustement 6

**Comment by ymajoros** [comment]
Then we need to add a position field (optional?) on ItemSale, and sort by position+date.
