### ISSUE TITLE
display full item/variant refs in sale

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#138]
Always display item ref (the most important) + variant ref.

May be small.

**Comment by cghislai** [comment]
With the default variant created with new items having the same ref as the parent item, shouldn't the variant ref be displayed only? I thought the variant ref would 'overwrite' the item ref. E.g item #REF001, variant #REF001-1 etc.. Currently the item ref is displayed as a hint when editing the variant ref.

**Comment by ymajoros** [comment]
It's more like REF001-blue, and "blue" is NOT the interesting part.
