### ISSUE TITLE
don't create ItemPicture if none uploaded

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#18]
Item picture is not mandatory, don't create one if none was given.

Check that you never assume there is one.

**Comment by cghislai** [comment]
Updated frontend code

**Comment by ymajoros** [comment]
Please close if done.

**Comment by cghislai** [comment]
i cant - you opened it

**Comment by cghislai** [comment]
I need to be added to the collaborators in repository settings

**Comment by ymajoros** [comment]
invited you... accept all invitations

**Comment by cghislai** [comment]
still no invite

**Comment by cghislai** [comment]
ok i missed it
