### ISSUE TITLE
mass import

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#19]
We need a way to mass import a catalog. We have hundreds of items that should be imported from our online store.

We could start with:

- a csv with products IDs and characteristics
- another one with names and descriptions, per language
- a zip with pictures, with some agreed upon format for file names ({id}-xxx.png, ...)

**Comment by ymajoros** [comment]
This is quite important, but I'd need your estimation.

How much time to have a simple file upload and maybe a few options, that would send a big zip to the backend and redirect to item list upon success?

**Comment by cghislai** [comment]
not much i guess. ill try to have something in the following hour

**Comment by cghislai** [comment]
I pushed an import view.
I tested it with the following item resource signature:


    @POST
    @Path("import")
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public void importItems(byte[] data) {
        System.out.println(data);
    }

**Comment by ymajoros** [comment]
Put it in /company/{id}/import.

Could you adapt frontend to use this, and close this issue?
