### ISSUE TITLE
Link Accounts to Point of sale

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#20]
According to our mail, accounts should be linked to points of sale
- Several account can be linked to a single point of sale 
-- AccoutSearch shold have a PosRef  field
- A Point of Sale should have a default account
-- defaultAcountRef field in (Ws)Pos

For the frontend interface:
- dropdown select the default account on pos edit
- Multi-checkbox select the linked accounts on pos edit
- dropdown select the point of sale  on sell view/payView ?
- only show linked accounts for payment method + emphasizes the default 

So we could have point of sale 'store - cash box 1' and 'store - cash box 2', and quickly switch between them while encoding sales.

**Comment by ymajoros** [comment]
AccountSearch does have a PosRef field. The search currently does not take this into account, it's something I need to fix (subquery). Anyway, just use it from now on, and use the returned accounts. You'll just see less accounts when fixed.

A POS shouldn't have a default account. It has multiple payment accounts (cash, debit card, credit, paypal, whatever ...). Vat accounts will probably be handled automatically by backend, at least for now (will maybe need some config later?).

POS is created at registration, and it's ok for now. POS edit isn't urgent.

**Comment by cghislai** [comment]
I just pushed basic POS edit before I saw your comment - without account linking yet though.

So for the frontend, we only need to fetch accounts from which to encode payment, for now

**Comment by ymajoros** [comment]
Yes, and the API is already there.

**Comment by cghislai** [comment]
done
