### ISSUE TITLE
ItemSale

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#21]
Implements ItemSale resource

Concerning the price: 
WsItemSale has a embedded WsPrice instance (no priceRef). Is it intended?

The frontend should probably only send dateTime, itemRef, quantity, saleRef (all required) and comment when creating an ItemSale.

**Comment by ymajoros** [comment]
Intended, but I could still change my mind ;-)

You'll really send a minimum and the backend will fill the gaps.

**Comment by ymajoros** [comment]
Changed my mind, by the way ;-) Still unsure, though.

Seems ok to me, untested but I guess it will work. Well, with minor changes anyway :-D
