### ISSUE TITLE
implements findItemSales

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#23]
In order to get back to an old sale, and if we want to show the user the items already in the sale.
An ItemSaleSearch with a NonNull saleRef field is probably enough.

**Comment by ymajoros** [comment]
done, untested (reopen if kaputt)

**Comment by ymajoros** [comment]
BTW, saleRef can be null, as you can search per item, too.

**Comment by ymajoros** [comment]
Just tested search, and it works. Didn't check POST/PUT/GET yet.
