### ISSUE TITLE
MoneyPile: link Front

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#28]

**Comment by cghislai** [comment]
This seems ok in frontend, but the backend does not seem to update the total amount of moneypiles and balance.

**Comment by ymajoros** [comment]
Please open an issue for that.

Le lun. 7 sept. 2015 à 13:15, cghislai <notifications@github.com> a écrit :

> This seems ok in frontend, but the backend does not seem to update the
> total amount of moneypiles and balance.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/28#issuecomment-138273211>.
>
-- 
Yannick Majoros
Valuya sprl
