### ISSUE TITLE
Frontend: documentation

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#31]
Could you write some basic doc for frontend?

- steps to create a new "screen"?
- ... with many fields (2-way binding?)
- internationalization?
- validation?
- things to know, quirks, ...

I suggest you start with a couple of lines per bullet, so I can quickly hack around if needed. We'll improve it later.

I'd say you have a 30 min time budget right now for the basic stuff. Just yell if you need more.

**Comment by ymajoros** [comment]
Format: asciidoc or markdown, anything that displays well in github.

**Comment by cghislai** [comment]
Pushed a first one.

**Comment by cghislai** [comment]
close if satisfying

**Comment by ymajoros** [comment]
where is it?

**Comment by cghislai** [comment]
README.dev.md

**Comment by ymajoros** [comment]
Looks good, but should have a further look.
