### ISSUE TITLE
Backend : add default 'unknown' item

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#36]
I just pushed adding custom items.
Currently, a item is created using POST /item then added as a regular item.

Questions:
- Should the user enter a reference for such items? Item.reference may not be null, so at the moment a made up one is used.
- I think those items should not be visible in the item list. they should be marked as custom.

**Comment by ymajoros** [comment]
Good question.

It's probably better to have a single "unknown" in catalog, and just allow to somehow edit its description.

Suggestion:

- remove custom item in sales
- let's add an "unknown" item in data (and let's create one at company registration)
- quantity / price should be freely editable
- ItemSale.comment can be used to edit some text (e.g. to later add this item to the catalog, see what has been really sold, ...)

I guess there is nothing to do in the front, behind removing custom items in sales, right?

**Comment by cghislai** [comment]
I don't have a strong opinion, but if it might be useful to know what has been sold, maybe is it better to just add a 'unknown' field in Item and be able to query them as other items?
I agree with point 3, freely editing prices as well.

**Comment by ymajoros** [comment]
I'm rather talking about just having an unknown item in catalog, priced at 1 €. If a customer buys something that's not in the catalog yet, the seller selects "unknown" instead of adding a custom item, and sets a quantity, a price and some comment. This way, we can just remove custom items in ItemSale.

**Comment by cghislai** [comment]
yes I'm fine with that.
I was considering the following case : You have a year of sales, and want
to check those items that are not in your catalog to see how you could
update it. Going through one year of sales comments sounds fastidious.

**Comment by cghislai** [comment]
Lets' do as you suggested

**Comment by ymajoros** [comment]
Yes:

- You should later be able to display all sales of some item (and thus "unknown" item too).
- You shouldn't wait 1 year for that.
- If you do, you probably don't care to have it in your catalog.
- For accountants, what really counts at the end of the year is having a total sale amount, and inventory change amount (2 numbers).

User is responsible to add this item in catalog, although I'll create one in "register" (later).

**Comment by ymajoros** [comment]
So, on frontend, just remove custom items on sale. User has to select some item from catalog (which can be a generic one but the frontend isn't concerned). 

Maybe we'll add an option to tag items as favorites, but that'll be another issue.

**Comment by cghislai** [comment]
done

**Comment by ymajoros** [comment]
I'll do the frontend, then.

**Comment by ymajoros** [comment]
Added that in /register
