### ISSUE TITLE
Backend: Allow editing ItemSale price

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#37]
Allow editing sale items price in line, just like reduction and amount

**Comment by cghislai** [comment]
We need to agree on ItemSale fields, this is ambigous.

ItemSale.vatExclusive should be the price of a single item (up to know I was thinking this would be the total amout, but we need to be able to edit price). 
Maybe a ItemSale.totalVatExclusive would be nice.

**Comment by cghislai** [comment]
I pushed price editing.
I leave this open for the backend.

**Comment by ymajoros** [comment]
OK let's add total per item, vatExclusive is per unit.

**Comment by ymajoros** [comment]
Added a 'total' field in ItemSale.

**Comment by ymajoros** [comment]
Please note that I got null vatRate for some ItemSale, which isn't allowed. I need to activate bean validation, so you can't pass that. I'll open a ticket for that, but you need to pass a valid vatRate.

**Comment by cghislai** [comment]
When updating an ItemSale with a custom price, the backend persist the item price (not the custom one). 
Fetching it afterwards loses the custom price. 

The ItemSale total is correctly updated (with custom price). But not the sale total.

**Comment by cghislai** [comment]
I check null vatRate

**Comment by cghislai** [comment]
Hmm, ItemSale vatRate is taken from the Item vatRate.
Item vatRate can't be null, and creating/editing an Item will never result in the  Item vatRate to be set to null.
Maybe you have old items, try editing them then saving to make sure vatRate is set.

**Comment by ymajoros** [comment]
Maybe. Let's close for now.
