### ISSUE TITLE
Frontend: can edit % on item sale with 2 decimals, displays 0

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#41]
I can enter "-2.25%" but it displays "2%".

**Comment by cghislai** [comment]
What do you prefer, allowing decimals?

**Comment by ymajoros** [comment]
I'll ask the customer :-)

**Comment by ymajoros** [comment]
The customer says no decimal in discounts, nowhere. :-) 

der Kunde ist König

**Comment by cghislai** [comment]
pushed
