### ISSUE TITLE
Frontend: validation buttons

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#42]
For every control that accepts ENTER, there should be a green V near the red cross to validate.

**Comment by cghislai** [comment]
I pushed that for the sale items inputs in command view.
However, you wanted to apply change on blur (on tab, or loose of focus), so clicking anywhere will apply the changes. An invalid value will reset the field. Only escape can discard entered changes and revert back to the old value.

**Comment by ymajoros** [comment]
Ok, so let's have a green V image that does nothing more, and a X that cancels, so that:

- ENTER or [green button] or clicking anywhere commits the sale
- ESC or [red button] cancels the sale

What do you think?

**Comment by cghislai** [comment]
Im fine with that.
However, we have a red cross for removing an item of the list. When editing inline in lists, if we keep that red cross for dismissing edit, that might be misleading.
Maybe a minus sign for removing item from lists? Or a block symbol (circle with a diagonal) for cancelling? input?

**Comment by ymajoros** [comment]
Le 8/24/2015 9:41 AM, cghislai a écrit :
>
> Im fine with that.
> However, we have a red cross for removing an item of the list. When 
> editing inline in lists, if we keep that red cross for dismissing 
> edit, that might be misleading.
> Maybe a minus sign for removing item from lists? Or a block symbol 
> (circle with a diagonal) for cancelling? input?
>
>

Both suggestions sound good ;-)

**Comment by cghislai** [comment]
There is an issue with this approach.
If we validate on blur, then when clicking on the cross (cancel), the blur event will fire first, the controller will validate the input, the input field will be removed and replaced with the updated value. 
I opt for discarding changes on blur. The user has to validate its input.

**Comment by ymajoros** [comment]
Could you disable all other controls on page, so that only commit (or
enter) / cancel (or escape) can be selected?

**Comment by cghislai** [comment]
Yes, but that does not solve how to handle blur event

**Comment by ymajoros** [comment]
Well, if you do that, we don't need blur anymore.

**Comment by cghislai** [comment]
pushed.
