### ISSUE TITLE
Frontend: handle request errors

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#43]
Currently, only the login form request errors are handled.

Something must be done for services handling background requests. They hold the Promise chain for performing requests and never pass it back to controllers. The controllers should be able to pass a function for dealing with errors. Something like

myService.addItemToASale(sale: ASale, item: Item, onError: (error)=>any);

**Comment by ymajoros** [comment]
Do what's best, but I don't know. I think it would be best to have global error handling code that can be somehow injected wherever necessary. Or a catch-all exception handler. Anything that doesn't need boilerplate stuff to be passed around. But I don't know what's best or how to do it in angular 2, so you decide ;-)

**Comment by cghislai** [comment]
Usually, when performing a request in a service I return a Promise (async task), and the controller can act on success or error.
Thinking of it, I think this is feasible in all cases.

**Comment by ymajoros** [comment]
What's feasible? ;-)

**Comment by cghislai** [comment]
returning the async task in all cases, so controller can act on error.
