### ISSUE TITLE
Frontend: Payments

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#45]
Just to be sure how payments should be handled in frontend.

Should I just prepare an AccountingEntry list while the user add payments methods, then send them all (plus the one for the returning cash i guess) to the backend?
Or should I send create/update/delete requests as the user adds/edits or removes pay methods?
Currently frontend uses the latter one.

Also, should I close accounting entries (i think this method was in the API doc)? (They will all be at the same time then)
And also, should I fetch the paid/remaining amount from the backend, or handle it locally?

**Comment by ymajoros** [comment]
See other issue I just discussed: backend will mark the sale as cancelled on delete, mark accounting entries as confirmed upon sale close, and possibly delete them on sale deletion too.

**Comment by cghislai** [comment]
So fontend should not close accounting entries.
Remaining questions:
- Should it send create requests as the user add payment methods? (it currently does)
- Should it fetch somehow the payment state from the backend (paid/remaining), or is it ok to compute it in the frontend?

**Comment by ymajoros** [comment]
It should create accounting entries linked to the sale's accounting
transaction, so we can redisplay the payment screen when necessary.

Do we already have something to know how much remains to be bayed? We
should have something like this and compute it in the backend. It's ok to
wait for a few seconds to get the balance to pay (at most, usually more
like 200 ms I guess).

**Comment by cghislai** [comment]
Nothing yet.
Maybe we could add some fields to Sale?

either way, I'll do like how I did for adding item to a sale : I calc the totals locally, then update when I get a response.

**Comment by cghislai** [comment]
I'll open a new one for the total, so we can close this one
