### ISSUE TITLE
Backend: mark sale as cancelled on DELETE /sale/{saleId}

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#46]
When starting to pay a sale, accounting entries are created.
If the user click on back button, then switch to a new sale, the sale is still in the open sale list. 
When the user wants to delete such sales, the server throws:

```
Cannot delete or update a parent row: a foreign key constraint fails (`comptoir`.`accounting_entry`, CONSTRAINT `FK_accounting_entry_accounting_transaction_id` FOREIGN KEY (`accounting_transaction_id`) REFERENCES `accounting_transaction` (`id`))
```

Should I make sure all accounting entries are removed when leaving the pay screen?

**Comment by ymajoros** [comment]
No, the backend should do it.

The thing is, I don't really want to do this. I'd rather have a "cancelled"
flag on sale. All sale searches would check this, so cancelled sales
wouldn't be shown unless explicitely asked.

**Comment by cghislai** [comment]
But it should be possible for the user to get back to the command view
(adding item) from the pay view.
What if, while adding pay amounts, the user realize there is an error in
the command? He clicks back, then add item.
When he gets back to the pay view, existing pays should be there (if the
customer already paid some amount with his card, for instance)

**Comment by ymajoros** [comment]
So, to re-state from the beginning:

- Sales shouldn't be deleted, but marked as cancelled instead. The backend
should do this when "DELETE" is called.
- Accounting entries aren't deleted now. Now, they should be confirmed
somehow, and the backend should do this when a sale is closed, or even
delete them when a sale is cancelled (as there hasn't be any accounting
operation anyway).

So, everything is backend-related, just leave the frontend as-is.

Agree?

**Comment by cghislai** [comment]
Agree.

**Comment by cghislai** [comment]
Looks like open sale are removed when calling DELETE, and accounting entries removed as well.
Should we be able to cancel closed sales for beta?

**Comment by ymajoros** [comment]
I think closed sales shouldn't be deleted or even cancelled. Cancelling a closed sale really means adding new reverse accounting entries. It is never cancelled.

**Comment by cghislai** [comment]
So this can be closed i guess - cancelling open sales works as intended
