### ISSUE TITLE
Backend: compute Sale paid amount / to be paid amout

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#47]
and expose it through sale resource?

**Comment by ymajoros** [comment]
Seems consistent with what to do.

There is something that's not quite right for me: our objects have input AND output fields, but could be separated, e.g. ItemSale contains its calculated cost once saved instead of returning another object type. But let's keep it like this for now.

**Comment by cghislai** [comment]
I agree, I find it confusing sometimes.
But I don't think another object must be returned, because this applies to other fields as well (I'm thinking of transactionRef for sales).
We should be able to mark some fields as input field, that clients must fill for requests. All other values would be discarded. Any missing value would throw an exception.
Maybe the backend could throw an exception as well when non-input fields are not null, but that would require resetting all the (non-input) object fields on the client side.

**Comment by ymajoros** [comment]
It would definitely be easier to separate objects. I wouldn't agree for
Sale.accountingTransaction, as it's not really an input field (can be input
& output), it's just some optional value. But we could have a SalePrice
calculated from ItemSale, with a total for the sale expressed as SalePrice
too. This is actually what I now (partly) do for the backend. ItemSale is
really the input, SalePrice is calculated from that and could be discarded.
They appear in quite different situations, so splitting them would make
sense. Some methods would take ItemSale, some would return SalePrice. No
confusion possible. Rather that than throwing exceptions at runtime when
some input/output combinations is used.

Now, just to be pragmatic, let's keep it as is for now.

**Comment by ymajoros** [comment]
To be clear, we should focus on concepts rather than input/output.

Some concepts always map to input/output. Other don't.

ItemSale and payed price (with taxes), per item or total by sale, are different concepts.

**Comment by ymajoros** [comment]
Added /sale/{id}/payed method that will give you the total. So, you need to call it whenever you need to calculate the total. This isn't stored anywhere, this is just for display. I'll leave the difference calculation and display to the frontend, as I don't think a web service for that would be a good thing.
