### ISSUE TITLE
Frontend: quantity edition is broken

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#50]
Change from 2x12 € to 2x100€, commit --> it's reverted to 2x12 €.

**Comment by cghislai** [comment]
This still fails with your last commit - price is overridden in ItemSaleService.saveItemSale

**Comment by ymajoros** [comment]
Didn't test yet. I'll check it.

**Comment by ymajoros** [comment]
Pushed something, broke something else but I think it's your fault ;-)
(frontend sends POST for existing ItemSale...). I'll open a ticket for that.

Le mer. 26 août 2015 à 12:59, Yannick Majoros <yannick@valuya.be> a écrit :

> Didn't test yet. I'll check it.
>
> Le mer. 26 août 2015 à 12:25, cghislai <notifications@github.com> a
> écrit :
>
>> This still fails with your last commit - price is overridden in
>> ItemSaleService.saveItemSale
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Valuya/comptoir/issues/50#issuecomment-134935952>.
>>
> --
Yannick Majoros
Valuya sprl

**Comment by ymajoros** [comment]
Changed my mind, let's continue with the discussion here.

Could you use PUT for existing items? If you think it's ok to have POST for both creation/update, and if that makes life easier for you, we could discuss it.

**Comment by cghislai** [comment]
I noticed the POST request, normally its fixed in master with my last
commits.
Its a typo cause I introduced new methods in the client and probably copy
pasted too much :/

Lets keep PUT for updates
