### ISSUE TITLE
Backend: implement pagination everywhere.

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#57]
Generic or specific (maybe we don't have that much requests).

**Comment by cghislai** [comment]
Question: How to sort on LocaleText fields?

**Comment by ymajoros** [comment]
Displayed lang should be passed, so we can select it for search.

**Comment by ymajoros** [comment]
We should add a SearchLocale in *Search that require searching in LocaleText.

**Comment by cghislai** [comment]
Ill move that in another issue

**Comment by cghislai** [comment]
Im on it
