### ISSUE TITLE
Frontend: split Item/ItemVariant

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#58]
Finish refactoring, make it work.

Backend code pushed, still needs some validation.

**Comment by cghislai** [comment]
I also pushed my changes.
It's a bit broken on both sides currently.

**Comment by ymajoros** [comment]
;-) LOL

Le jeu. 3 sept. 2015 à 14:37, cghislai <notifications@github.com> a écrit :

> I also pushed my changes.
> It's a bit broken on both sides currently.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/58#issuecomment-137423656>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
This looks good. Probably needs some more testing, ill close afteward.
