### ISSUE TITLE
Backend: item resource

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#68]
Now we have the /item resource dealing with itemvariant.
It should be renamed to /itemvariant and a /item resource should be created to deal with items.

**Comment by ymajoros** [comment]
Yeah, I started doing just that. Will try to push at 13.00.

Le ven. 4 sept. 2015 à 09:29, cghislai <notifications@github.com> a écrit :

> Now we have the /item resource dealing with itemvariant.
> It should be renamed to /itemvariant and a /item resource should be
> created to deal with items.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/68>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
Damn I have something as well now :/
Will make a request

**Comment by ymajoros** [comment]
Can we close this one?

**Comment by cghislai** [comment]
Yep, a new PR in the queue for splitted searches
