### ISSUE TITLE
Point of Sale: implements

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#8]
- classe PointOfSale
- avec une config liée aux divers compte :
* compte vente par défaut (éventuellement d'autres : services, ...)
* comptes de payements : bancontact, cash, paypal, contactless, visa online, ...
- on peut avoir plusieurs caisses : par exemple, samedi, il y en avait une dehors et une dans le magasin

**Comment by ymajoros** [comment]
Just pushed, will close if we agree it's complete.

**Comment by ymajoros** [comment]
Works for me, can you close if ok?

**Comment by cghislai** [comment]
Works fine.
However, aren't we still missing linking to account, Ill open another issue for that.
