### ISSUE TITLE
Frontend: make it fast and fluent

### ISSUE THREAD

**Issue by ymajoros** [Valuya/comptoir#91]
Seems to be blocked quite often. I quickly ran Chrome's js profiler, and it seems to be stuck in NumberFormatter.format a lot. I guess there are other things.

I'd want everything to be non-blocking.

Search-as-you-type can have some delay between letters.

I'm under the impression that there still are some concurrency problems, too: when clicking on "+" on the ± spinner for unit count in a sale, it displays numbers in a strange order: 1 2 3 ... 12 9 13 14 ...

Please take some time to go through all screens again, trying to act as someone who will handle customers.

**Comment by cghislai** [comment]
should be ok now
