### ISSUE TITLE
frontend: implement table column weights

### ISSUE THREAD

**Issue by cghislai** [Valuya/comptoir#98]
Long text in table cells overflows.

One quick solution is to wrap columns content inside an absolute-positioned div anchored to the cell boundaries. 
On the down side, the row height must then be fixed, and cell width will be distributed equally.

A better solution would probably be specifying column weights in our model, then specifying the width on each column element. fixed-width columns can hide text overflow.

**Comment by ymajoros** [comment]
The problem is that, at first, we see some long text. Then it disappears on
click. Then reappears again. Selection etc. is quite difficult.

Le jeu. 29 oct. 2015 à 22:12, cghislai <notifications@github.com> a écrit :

> Long text in table cells overflows.
>
> One quick solution (soon to be pushed) is to wrap columns content inside
> an absolute-positioned div anchored to the cell boundaries.
> On the down side, the row height must then be fixed, and cell width will
> be distributed equally.
>
> A better solution would probably be specifying column weights in our
> model, then specifying the width on each column element. fixed-width
> columns can hide text overflow.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/98>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
It should work once the cells do not overflow out of their expected bounds.
Shall we also disable escaping the html tags in item descriptions?

**Comment by ymajoros** [comment]
We can't know if cells overflow. What about max-width?

Yes, we shouldn't escape the description. It can come from anywhere,
Prestashop in our case; Any (simple) way to make sure it's valid html?

Le jeu. 29 oct. 2015 à 22:40, cghislai <notifications@github.com> a écrit :

> It should work once the cells do not overflow out of their expected bounds.
> Shall we also disable escaping the html tags in item descriptions?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/98#issuecomment-152336341>.
>
-- 
Yannick Majoros
Valuya sprl

**Comment by cghislai** [comment]
Max-width cannot be set on the table. max-width on the cell itself can only be set if we know how much width the cell can take (2 cells of max-width  100% might lead to a table of width 200%). So we have to compute width based on weights. I think this is what responsive CSS frameworks do.

It looks like Element.innerHTML makes the HTML valid ( If the string contains HTML tags, the string is parsed and formatted as it is placed into the document.) + quick test. However, we have to trust the source.

**Comment by ymajoros** [comment]
ok

Le ven. 30 oct. 2015 à 12:42, cghislai <notifications@github.com> a écrit :

> Max-width cannot be set on the table. max-width on the cell itself can
> only be set if we know how much width the cell can take (2 cells of
> max-width 100% might lead to a table of width 200%). So we have to compute
> width based on weights. I think this is what responsive CSS frameworks do.
>
> It looks like Element.innerHTML makes the HTML valid ( If the string
> contains HTML tags, the string is parsed and formatted as it is placed into
> the document.) + quick test. However, we have to trust the source.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Valuya/comptoir/issues/98#issuecomment-152503017>.
>
-- 
Yannick Majoros
Valuya sprl
